version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ez-aigent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ez-aigent

  dashboard:
    build: https://github.com/empow3r/EzAigents.git#main:dashboard
    container_name: ez-aigent-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - NEXT_TELEMETRY_DISABLED=1
      - DASHBOARD_PORT=3000
      - DASHBOARD_HOST=0.0.0.0
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEYS=${DEEPSEEK_API_KEYS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - ENABLE_MONITORING=true
      - ENABLE_CHAT=true
      - ENABLE_3D_WORKSPACE=true
      - ENABLE_VOICE_COMMANDS=false
      - ENABLE_AUTO_DOCUMENTATION=true
      - ENABLE_SECURITY_SCANNING=true
    depends_on:
      - redis
    networks:
      - ez-aigent

volumes:
  redis_data:

networks:
  ez-aigent:
    driver: bridge