services:
  redis:
    image: redis:7-alpine
    container_name: ezaigents-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  claude-agent:
    build:
      context: .
      dockerfile: Dockerfile.enhanced-agent
      args:
        AGENT_TYPE: claude
    container_name: ezaigents-claude
    environment:
      - AGENT_ID=claude-docker-001
      - REDIS_URL=redis://redis:6379
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./.agent-memory:/app/.agent-memory
      - ./logs:/app/logs
      - ./src:/app/src