services:
  redis:
    image: redis:7-alpine
    container_name: ezaigents-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  claude-agent:
    build:
      context: .
      dockerfile: Dockerfile.enhanced-agent
      args:
        AGENT_TYPE: claude
    container_name: ezaigents-claude
    environment:
      - AGENT_ID=claude-docker-001
      - AGENT_TYPE=claude
      - REDIS_URL=redis://redis:6379
      - CLAUDE_API_KEY=test-key-please-replace
      - NODE_ENV=development
      - COORDINATION_ENABLED=true
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./.agent-memory:/app/.agent-memory
      - ./logs:/app/logs
      - ./src:/app/src
    command: ["node", "/app/agent/docker-safe-index.js"]