version: '3.8'

services:
  # Redis only - for development with local Node.js
  redis:
    image: redis:7-alpine
    container_name: ezaigents-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Dashboard in development mode with hot reload
  dashboard-dev:
    image: node:18-alpine
    container_name: ezaigents-dashboard-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./dashboard:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  redis-dev-data: